// Auto-generated by gltots.py
export type FragmentShaderAttributes = "fColor"
export type FragmentShaderVaryings = "finalColor"
export default class FragmentShader {
static getAttributeLocation(gl: WebGL2RenderingContext, program: WebGLProgram, item: FragmentShaderAttributes): number { return gl.getAttribLocation(program, item) }
static src = "# version 300 es\n\nprecision mediump float;\nin vec4 fColor;\nout vec4 finalColor;\n\nvoid main(void) {\n    finalColor = fColor;\n}"
}
