// Auto-generated by gltots.py
export type VertexShaderAttributes = "a_position" | "a_color"
export type VertexShaderVaryings = "fColor"
export type VertexShaderUniforms = "worldMatrix" | "viewMatrix" | "projMatrix"
export default class VertexShader {
static getAttributeLocation(gl: WebGL2RenderingContext, program: WebGLProgram, item: VertexShaderAttributes): number { return gl.getAttribLocation(program, item) }
static getUniformLocation(gl: WebGL2RenderingContext, program: WebGLProgram, item: VertexShaderUniforms): WebGLUniformLocation { return gl.getUniformLocation(program, item) }
static src = "# version 300 es\n\nin vec3 a_position;\nin vec3 a_color;\n\nuniform mat4 worldMatrix;\nuniform mat4 viewMatrix;\nuniform mat4 projMatrix;\n\nout vec4 fColor;\n\nvoid main(void) {\n    fColor = vec4(a_color, 1.0);\n    gl_Position = projMatrix * viewMatrix * worldMatrix * vec4(a_position, 1.0);\n}  "
}
